- src/Options.cpp
- src/Options.h
- src/dllmain.cpp
- src/options_patch.cpp
Even though all the INI settings have already been dumped by others, it could come in useful to have this feature for any future game updates.
The code for it also lets us track all the GameProperty pointers too, in case we ever need to read/write from any of them.
(Also made it so SSR will be disabled automatically if AA is disabled, like mentioned in #101)
E: btw to test this I had to add MH_Initialize() inside dllmain's Initialize, I'm guessing the MinHook changes are maybe WIP though so didn't include that change here.
> Add "dump_game_options" option for dumping hidden INI settings

- src/Options.cpp
- src/Options.h
- src/disable_intro_movies.cpp
- src/dllmain.cpp
Added a way to disable intro movies mostly as described at https://github.com/yamashi/PerformanceOverhaulCyberpunk/issues/75#issuecomment-747723572, except I changed it to break the name hashes of those variables via a hook instead of needing to patch in jump calls around them, should make it easier to port across versions I think.
Still a pretty hacky workaround though, hopefully a better solution will be found eventually, but I've spent many hours trying different things and this variable breaking method was the best result I've had so far.
Like mentioned on that comment the audio for intro will still play, but the game should let you get to the "press space to continue" screen a little bit quicker than with the intro video, maybe goes even faster with better machines too. (this also …
> Initial impl. of disable_intro_movies

- src/Options.cpp
- src/Options.h
- src/overlay/Overlay.cpp
The end-user will need to refer to the [virtual key codes](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) if they wish to change it. This should resolve #133.
> Made the console key configurable

- xmake.lua
This PR disables gamepad support in imgui, which required XInput and was causing CET to (attempt to) load a different version of XInput than the one used by the game.
> [imgui] Remove XInput dependency

- src/dllmain.cpp
Properly dispose of minhook on shutdown.
> Uninitialize minhook and Overlay (if console true) during Shutdown()

- src/stdafx.h
- xmake.lua
I suggest moving WIN32_LEAN_AND_MEAN to xmake.lua.
I believe it should be moved from its current location, as other files could include Windows.h which this mainly relates to.
If not moving it into xmake.lua, at least I would move it up a bit in stdafx.h, as now, it is in weird place in general in my opinion.
> Move WIN32_LEAN_AND_MEAN define to xmake.lua

- src/dllmain.cpp
- src/overlay/Overlay.cpp
Modified a bit shutdown procedure again... Hopefully last time for a while. 
Also corrected style in dllmain with this commit, as I found out it stands out when compared to others.
> Move kiero::shutdown to Overlay destructor, change code style in dllmain

- src/common/D3D12Downlevel.h
- src/kiero/kiero.cpp
- src/kiero/kiero.h
- src/overlay/Overlay.cpp
- src/overlay/Overlay.h
- src/overlay/Overlay_D3D12.cpp
- src/overlay/Overlay_Hooks.cpp
This PR adds support for Windows 7 to the overlay, using Direct3D12 with D3D12On7 as discussed in #134.
Notes on implementation:
- I've mostly kept to the naming scheme Microsoft uses when it discusses D3D12 on Windows 7. This means that variables and functions specific to Windows 7 are suffixed with 'downlevel' to distinguish them from common D3D12 functionality.
- Two hooks have been added: `PresentD3D12Downlevel` and `CreateCommittedResource`. These functions are only hooked on Windows 7. The `PresentD3D12Downlevel` hook serves the same purpose as the current `Present` hook but for Windows 7, where Present is called on the device and not on the swap chain. The  `CreateCommittedResource` hook is required to find the backbuffer addresses, since there is no swap chain to query these from. …
> Add Windows 7 support to overlay

- src/dllmain.cpp
- src/overlay/Overlay.cpp
- src/overlay/Overlay.h
- src/overlay/Overlay_D3D12.cpp
Few smaller fixes, didnt wanted to pull each one separately...
- fix problem with unselectable console items
- change a bit Overlay's Initialize/Shutdown again (CTD at exit is not yet fixed still, some more debugging to do... if we want to just F it, we could remove Overlay::Shutdown from picture temporarily...)
- pulled out that reset lambda from InitializeD3D12 as was proposed in #318
- do not call reset inside InitializeImGui, it should have not been there (prolly nothing bad in the end, but was redundant to say the least)
Wanted to do other Overlay changes to things that got added... But as I cannot debug these changes, I rather play it safe... And just pulled that single function out, leaving other things as they were.
Hope @Mattiwatti gets around eventually to finish it.
> Minor fixes

- src/overlay/Overlay.cpp
Small quality of life change: make it so that pressing the console key will focus the overlay's text input field so it's possible to begin typing immediately.
It looks like this was already the intended behaviour, only `ImGui::SetKeyboardFocusHere()` was being called after creating the widget, whereas the docs say that it applies focus to the *following* widget (which didn't exist because the text input is the last widget added).
> [overlay] Make text input grab keyboard focus

- src/scripting/Scripting.cpp
I've added some logic that checks if the first argument of `pFunc` expects a `ScriptGameInstance` before injecting the instance.
This enables calling of functions that don't require a `ScriptGameInstance`.
For example, calling `Game.GetFunFact()` without this PR will return `Function 'Game.GetFunFact' expects 4294967295 parameters, not 0`, whereas with the PR, it will call and return that function.
I haven't touched C++ for almost 20 years so apologies for any mistakes. Tested against master and 1.06.
Note: Build will fail because lua.org's SSL certificate expired earlier today.
> Allow calling functions that don't expect ScriptGameInstance

- src/overlay/Overlay_D3D12.cpp
- src/overlay/Overlay_Hooks.cpp
- Revert 2facdc7 (resize detection); was causing CTD even if not resizing for some users. Resize detection will have to be done some other way (if at all possible reliably on Windows 7, since there is no swap chain)
- Initialize `m_outWidth` and `m_outHeight` in `InitializeD3D12Downlevel` so that console properly spans the entire window width on Windows 7
> D3D12on7 changes

- src/overlay/Overlay.cpp
This PR splits the Log() output into lines as `ImGuiListClipper` is designed to work with mostly-uniformly sized rows. This fixes the issue where console can't scroll to the bottom when `Dump()` output is bigger than the console.
> Split Log output by newline

- README.md
- src/Options.cpp
- src/Options.h
- src/d3d12/D3D12_Hooks.cpp
The game always passes `D3D12_DOWNLEVEL_PRESENT_FLAG_WAIT_FOR_VBLANK` to `ID3D12CommandQueueDownlevel::Present` regardless of the actually selected VSync setting. This means FPS is limited to 60 on Windows 7 no matter what.
This PR adds an option to disable VSync on Windows 7 by stripping the flag in the `D3D12::PresentDownlevel` hook.
> Add disable_win7_vsync to options

- src/d3d12/D3D12.h
- src/d3d12/D3D12_Functions.cpp
- src/d3d12/D3D12_Hooks.cpp
This is a fixed version of the (now reverted) resize detection on Windows 7 that was added in 2facdc7, which was causing crashes to desktop for some users. This version has been tested and verified working by a user who was getting CTDs with the previous version.
Apart from working resize handling, the backbuffer index is now found using a better method than the naive `+= 1` strategy that was being used previously. The index of the passed-in buffer is found using a reverse lookup in the known list. If the buffer is not found, a window resize is assumed and the D3D12 state is reset.
> [d3d12on7] Refactor backbuffer indexing and handle resizes

- src/sol_imgui/README.md
- src/sol_imgui/sol_imgui.h
@Nats-ji pointed out this issue :P 
That text_end argument was just retarded for Lua, doesnt make any sense for it.
> Fix ImGui.CalcTextSize overloads (Lua bindings)

- src/Options.cpp
- src/d3d12/D3D12.h
- src/d3d12/D3D12_Functions.cpp
- src/d3d12/D3D12_Hooks.cpp
- src/imgui_impl/dx12.cpp
- src/imgui_impl/dx12.h
This fixes a number of issues on Windows 7 (also see issue #429):
- Changed imgui to reuse the game's D3D12 command queue rather than making a new one. This fixes a crash on Windows 7 and ensures the GPU node index of the command queue always corresponds to the mask used by the game.
- Fixed D3D12 backbuffer index finding on Windows 7 with v1.10.
- Fixed window resizes breaking the overlay on Windows 7 with v1.10.
~~An unresolved issue on Windows 7 currently is zombie `Cyberpunk2077.exe`s sticking around after exiting the game.~~ Also fixed.
> Fixes for v1.10 on Windows 7

- src/dllmain.cpp
This fixes a crash in REDEngineErrorReporter.exe after the game exits.
> Do not flush spdlog on shutdown in the error reporter process

- src/imgui_impl/win32.cpp
- src/sol_imgui/README.md
- src/sol_imgui/sol_imgui.h
- Enabled ImGui keyboard navigation (Following @WSSDude420 's instruction 😄 )
- Removed the deprecated argument of Drag and Slider widgets, replace it with the newer ImGuiSliderFlag in sol_imgui.h
- Fixed space and tab mix up and alignment in sol_imgui.h
- Made the argument `open` optional in  ImGui.Begin(), ImGui.BeginModal(), ImGui.BeginTabItem(), so the close button can be hidden when setting flags.
- Added bindings for the new table widgets in ImGui 1.8.0
> Enable ImGui keyboard navigation and sol_imgui.h update/fix

- src/reverse/StrongReference.h
- src/reverse/TweakDB.cpp
- src/reverse/TweakDB.h
- src/reverse/WeakReference.h
- src/scripting/Scripting.cpp
- src/stdafx.h
This requires latest RED4ext.SDK.
• TweakDB:GetFlat(...):
Parameter: flat DBID
Return: value or nil
• TweakDB:SetFlat(...):
Parameter: flat DBID
Return: true on success
Note: FlatValues are pooled. Our value pool is initialized on the first call to TweakDB::SetFlat
• TweakDB:GetRecord(...):
Parameter: record DBID
Return: StrongReference or nil
• TweakDB:Query(...):
Parameter: query DBID
Return: array or nil on failure
• TweakDB:Update(...):
Parameter: record DBID or a record handle
Return: true on success
Note: I was thinking about adding "TweakDB::UpdateAllRecords" but i think mods would abuse it, it will tank performance.
Query
Record
Getting/Setting a flat value then "updating" the record to point to the new value
> TweakDB binding

- src/reverse/LuaRED.h
This fixes the annoying "expecting userdata got XX"
it also lets Scripting::ToRED return nullptr in stackType.value so you could add logs in your code for the expected type.
It shouldn't cause any issues with any mod
I do it in TweakDB::SetFlat
```cpp
RED4ext::CStackType stackType = Scripting::ToRED(aValue, stackTypeCurrent.type, &s_scratchMemory);
if (stackType.value == nullptr)
{
RED4ext::CName typeName;
stackTypeCurrent.type->GetName(typeName);
spdlog::get("scripting")->info("[TweakDB::SetFlat] Failed to convert value. Expecting: {}", typeName.ToString());
return false;
}
```
> Converter::ToRED - LuaRED implicit conversion should only be for numbers

- src/reverse/LuaRED.h
An issue with out args of non-scalar types was found.
```
import function GetQuestMappinPosition(mappinHash : Uint32, out position : Vector3) : Bool;
```
This call `args[i] = Scripting::ToRED(sol::nil, apFunc->params[i]->type, &s_scratchMemory);` for creating a placeholder for the out arg was resulting in an empty value because of the condition `if (!CheckObjectType || aObject.is<T>())` since `sol::nil` has no type and can't be checked with `.is()`.
Command for testing (works in Main Menu):
```
print(Game.GetMappinSystem():GetQuestMappinPosition(0))
```
> Fix LuaRED converter for nils

- src/scripting/LuaSandbox.cpp
- src/scripting/Scripting.cpp
- xmake.lua
Adds left out define needed for sol to actually utilize LuaJIT (right now, it just uses Lua 5.1 thanks to it)
Also adds and whitelists bit library, as bit-wise ops are missing in older Lua (accessible with bit32 from within Lua).
> Add bit lib (accessible with bit32), actually use LuaJIT with sol3

- src/overlay/Overlay.cpp
- src/overlay/Overlay.h
- src/overlay/widgets/HelperWidgets.cpp
- src/overlay/widgets/TweakDBEditor.cpp
- src/overlay/widgets/TweakDBEditor.h
- src/overlay/widgets/Widget.h
- src/reverse/TweakDB.cpp
- src/reverse/TweakDB.h
- src/scripting/LuaVM.cpp
- src/scripting/LuaVM.h
- src/scripting/LuaVM_Hooks.cpp
- src/scripting/Scripting.cpp
- src/stdafx.h
This pull request needs https://github.com/WopsS/RED4ext.SDK/pull/30
• All TweakDB functions can now be called with strings instead of TweakDBID
```lua
TweakDB:SetFlat('my.flat', 1)
TweakDB:SetFlat(TweakDBID.new('my.flat'), 1)
```
• Added CloneRecord, CreateRecord and DeleteRecord
returns true/false
No idea how save files handle this. Creating items seems to work without issues
Be sure to check if a save file with your mod still loads without your mod loaded
```lua
TweakDB:CreateRecord('UniqueName.MyVehicleRecord', 'gamedataVehicle_Record')
TweakDB:CloneRecord('UniqueName.MyVehicleRecord', 'Vehicle.av_militech')
TweakDB:DeleteRecord('UniqueName.MyVehicleRecord')
```
• Added GetRecords
Check out TweakDBEditor's 'Records' tab for a list of type names
```lua
local vehicleRecords = …
```
> TweakDBEditor + TweakDB changes

- xmake.lua
I have split mode-specific options for better granularity.
Also have set optimize level for all of them (was only set for release previously).
ImGui version was bumped to 1.82, there should be no problems.
Also, from now on, ImGui assertions will be disabled only for release mode. They are useful for debug/releasedbg I would say.
TiltedCore was updated to 0.2.1.
> Bumped ImGui version and updated mode-specific settings in xmake.lua

- src/Utils.cpp
- src/Utils.h
- src/reverse/Converter.cpp
- src/scripting/LuaSandbox.cpp
- src/scripting/Sandbox.cpp
This PR prevents users from overwriting tables of another mod by accident.
Deep copying is avoided inside LuaSandbox::Initialize on purpose, as that function just creates base templated environment for each Sandbox instance. Sandbox instance makes deep copy during construction.
Deep copy does not take into account duplicates, which should not really happen in our use case I believe. Did not found anything which would break cause of wrong copy.
We do not deep copy keys, so keys which are tables will not get properly copied (we do this only inside DeepCopySolObject function), but again, should not matter for our use case. Can be added relatively easily if required, have previous code saved which had this function in.
Before this, something like this could be done, affecting other mods in …
> Better isolation of sandboxed environments

- src/reverse/LuaRED.h
Hacky solution for LuaRED ToLua conversion of 64-bit integral types.
Abuses the fact that LuaJIT internally uses cdata for these types from scripts.
Thanks @psiberx for helping with this.
> Fix LuaRED ToLua conversion function for 64-bit integral types

- src/VKBindings.cpp
- src/VKBindings.h
- Changed std::queue and std::mutex combo to TiltedPhoques::TaskQueue for bind callbacks
- Fixed scroll wheel binding
- Fixed single inputs unable to be called at the same time
> Fixes and cleanup for VKBindings

- src/Utils.cpp
- src/d3d12/D3D12.cpp
- src/d3d12/D3D12.h
- src/overlay/widgets/Console.cpp
- src/reverse/TweakDB.cpp
- src/scripting/LuaVM.cpp
- src/scripting/LuaVM.h
- xmake.lua
- Added DelayedSetTrapInputInImGui function so we are able to trap input asynchronously at the right time (inside message queue seems to work always) [used by #529 ]
- Added ability to block mod drawing into LuaVM [used by #529]
- Fixed wrong TweakDB assertion
- Fixed DeepCopySolObject utility function for nil values
- Fixed issue with console history not copying over null terminator
> Smaller fixes and additions

- src/overlay/widgets/Bindings.cpp
- src/overlay/widgets/Bindings.h
- src/overlay/widgets/HelperWidgets.cpp
- src/overlay/widgets/HelperWidgets.h
- src/overlay/widgets/TweakDBEditor.cpp
- src/sol_imgui/sol_imgui.h
- Changed some ImGui::Text calls to ImGui::TextUnformatted to not unnecessarily invoke snprintf
- Added Reset Changes button to Bindings widget [new function is also used by #529 ]
- Added new helper widget for unsaved changes modal [used by #529 ]
- Made existing widgets a bit better [rest of additions are coupled inside #529 as that would not compile on its own in this state]
- Change definition for ImGui Text Lua binding to point to TextUnformatted, as we do not support formatting in current bindings implementation anyway. Should avoid some overhead from snprintf, as Text is commonly used element.
> Minor additions to UI

- src/imgui_impl/imgui_user_config.cpp
- src/imgui_impl/imgui_user_config.h
- xmake.lua
This PR will reenable assertions in release. Control for these new assertions can be found in #529 .
> Override ImGui asserts by custom definition for more granular control

- src/overlay/widgets/Bindings.cpp
Quick fix for "Cyber Engine Tweaks" being printed in Inputs tab of Bindings widget.
Small oversight... I removed the message, but forgot to remove heading x)
> Fix Bindings Input tab printing "Cyber Engine Tweaks"

- src/reverse/BasicTypes.cpp
- src/reverse/BasicTypes.h
- src/scripting/Scripting.cpp
EulerAngles::ToString had the roll and yaw values swapped because of incorrect parameter order in [Scripting.cpp](https://github.com/yamashi/CyberEngineTweaks/blob/master/src/scripting/Scripting.cpp#L183). I fixed this by rearranging the parameter order everywhere to be consistent with [EulerAngles.hpp](https://github.com/yamashi/RED4ext.SDK/blob/6438a96c0fe1e6e00a2815c97bbf51b1b0bdc9ee/include/RED4ext/Types/generated/EulerAngles.hpp#L16) (roll, pitch, yaw).
> Reorder roll, pitch, and yaw to be consistent with the internal order

- src/VKBindings.cpp
- src/reverse/BasicTypes.cpp
- src/reverse/BasicTypes.h
- src/reverse/Converter.h
- src/reverse/Enum.cpp
- src/reverse/Enum.h
- src/reverse/Type.cpp
- src/scripting/LuaSandbox.cpp
- src/scripting/LuaSandbox.h
- src/scripting/Scripting.cpp
1. Fixed out params handling when out params are not in the end of the param list.  
```
import function GetCurveValue(out x : Float, out y : Float, curveName : CName, isDebug : Bool);
import function GetObjectClosestToCrosshair(instigator : whandle:gameObject, out angleDistance : EulerAngles, query : gameTargetSearchQuery) : handle:gameObject;
```
2. Fixed CClassConverter for nils. This call `args[i] = Scripting::ToRED(sol::nil, apFunc->params[i]->type, &s_scratchMemory);` for creating a placeholder for the out param was resulting in a `nullptr` when param is not a handle.
```
import function LookAt(instigator : whandle:gameObject, out params : gameaimAssistAimRequest);
```
3. Comparison operators for basic types and concatenation for TweakDBID:  
```lua
print(Vector3.new(1, 2, 3) == …
```
> Fixes for out params, mod database, and lua operators for basic types

- src/scripting/GameOptions.cpp
- src/scripting/Scripting.cpp
- src/scripting/Scripting.h
1. Fix falsy "Unknown error" when calling a global that returns `nil`.
Examples of global calls that can return `nil`:
```lua
Game['GetMountedVehicle;GameObject'](Game.GetPlayer())
Game.GetUISystem()
Game.GetPlayer()
```
2. Return out params from global function the same way as for instance methods.
Examples of global functions with out params:
```lua
Game['ScriptedPuppet::GenerateLootModifiers;ScriptedPuppetarray<gameStatModifierData>'](Game.GetPlayer())
Game['AIActionHelper::GetActiveTopHostilePuppetThreat;ScriptedPuppetTrackedLocation'](Game.GetTargetingSystem():GetLookAtObject(Game.GetPlayer(), false, false))
```
3. Fix typo in `GameOption::Toggle`.
> Fix global calls and GameOptions.Toggle()

- src/reverse/LuaRED.h
It's not possible to use `aObject.as<T>()` on 64-bit value directly because it's a cdata in LuaJIT and not a number. 
The solutions is to use Lua's `tostring()` to get the string representation of the number packed in cdata and then convert it using `std::stoll` / `std::stoull`.
Test:
```lua
local entityId = NewObject('entEntityID')
entityId.hash = 16570246047455160070ULL
```
> Fix LuaRED ToRED conversion for 64-bit integral types

- src/reverse/Converter.cpp
- src/reverse/Converter.h
- src/scripting/FunctionOverride.cpp
- src/scripting/ScriptContext.cpp
1. Added reporting for errors occurred in `Observe` / `Override` handlers.
This fails silently before fix:
```lua
Observe('gameObject', 'OnGameAttached', function()
undefined.call()
end)
```
2. Added implicit string to `TweakDBID` conversion. 
```lua
print(Game.GetTransactionSystem():GetItemInSlot(Game.GetPlayer(), 'AttachmentSlots.WeaponRight'):GetItemID())
```
3. Removed redundant environment passing to Lua functions as an argument. This change addresses two issues:
a. Environment passed as an argument doesn't change the environment of the function, but goes straight to the called function as a table.
b. The function inherits environment when defined and the assignment is stored in the Lua state. There is no need to set environment for function before call unless it's intended to change …
> Error logging for Observe / Override, implicit TweakDBID conversion, minor environment fixes

- src/d3d12/D3D12_Functions.cpp
This small change should fix CET shutting down when executing D3D12::Initialize before D3D12::ExecuteCommandLists. This happens because ImGui relies on an existing commandQueue. Normally this isn't a problem because the game always calls those hooks in the correct order but some overlay software might call present before executecommandlist during initialization (In my case the specialK framework) and can cause cet to break. 
It even seems like the original code tries to take something like this into account but the order of the functions is mixed up.
> D3D12 - Ensure that ImGui_ImplDX12_CreateDeviceObjects never receives a nullptr command queue

- scripts/autoexec.lua
- src/Utils.cpp
- src/Utils.h
- src/reverse/BasicTypes.h
- src/reverse/ClassStatic.cpp
- src/reverse/ClassStatic.h
- src/reverse/Converter.cpp
- src/reverse/Converter.h
- src/reverse/Enum.cpp
- src/reverse/EnumStatic.cpp
- src/reverse/EnumStatic.h
- src/reverse/LuaRED.h
- src/reverse/RTTIHelper.cpp
- src/reverse/RTTIHelper.h
- src/reverse/RTTIMapper.cpp
- src/reverse/RTTIMapper.h
- src/reverse/SingletonReference.cpp
- src/reverse/SingletonReference.h
- src/reverse/Type.cpp
- src/reverse/Type.h
- src/scripting/FunctionOverride.cpp
- src/scripting/LuaSandbox.cpp
- src/scripting/LuaSandbox.h
- src/scripting/LuaVM.cpp
- src/scripting/Sandbox.cpp
- src/scripting/Scripting.cpp
- src/scripting/Scripting.h
- All game classes are directly accessible by name. For example, `entEntityId`, `PlayerPuppet`.
- All game enums are directly accessible by name. For example, `gamedataStatType.BaseDamage`, `gameGameVersion.Current`.
- Classes can also be accessed by their aliases from redscript. For example, `WeaponObject` instead of `gameweaponObject`.
- Classes have the conventional `.new()` constructor. For example, `MappinData.new()`.
- A constructor can take an array of properties to create and initialize an object in a single statement. For example, `EntityID.new({ hash = 12345 })`.
- Static methods are accessible from classes using the dot. For example, `ScriptedPuppet.IsDefeated(npc)`.
- A static method can be called from an instance if the first parameter is of the same type. For example, …
> New Script API, fixed crashes and memory leaks

- src/reverse/RTTIHelper.cpp
- src/scripting/Scripting.cpp
- Fixed a crash when passing an incompatible array as an argument. For example, an array of numbers instead of an array of handles.
- Fixed memory leak when passing an object instead of an array as an argument. This resulted in a silent crash without calling `ResetAllocator`.
- Fixed memory leak for arrays with elements of certain types passed as an argument. When array is filled, the element assignment has copy semantics. Intermediate values may leak because the destructor was not called for types that require the destructor call to be properly deallocated.
> Fix memory leaks and crash when working with DynArray

- src/reverse/BasicTypes.h
- src/reverse/RTTIHelper.cpp
- src/reverse/RTTIHelper.h
- src/reverse/ResourceAsyncReference.cpp
- src/reverse/ResourceAsyncReference.h
- src/scripting/FunctionOverride.cpp
- src/scripting/FunctionOverride.h
- src/scripting/LuaSandbox.cpp
- src/scripting/Scripting.cpp
- src/scripting/Scripting.h
- `Observe()` and `Override()` now accept both native and scripted type names.
- Improved overloaded functions handling. Prevents constant swapping when two overloads are used at the same rate.
- Improved detection of whether the game is running. Prevents more crashes when exiting the game.
- Added support for old style static calls `obj:Static(obj, args)`. Improves backward compatibility with 1.13 mods.
- Added support for `ResourceAsyncReference`. Allows editing of TweakDB props of that type by the mods,
- Fixed `CName` calculation for "None" (mirrors RED4ext logic).
- Added logging for errors occurred in the module loaded with `require()`. Should make the transition to the new version less painful.
- Added optional params support. For example, …
> Add ResourceAsyncReference support, small fixes and improvements

- src/reverse/RTTIHelper.cpp
- src/scripting/LuaVM.cpp
- src/scripting/LuaVM_Hooks.cpp
1. Fix when `s_scratchMemory.Reset()` is called for nested RTTI calls (can happen when overridden function is called by mod).
2. Bring back log count workaround for `onInit` handler as relying entirely on `SetLoadingState` introduces major breaking changes (player entity and some systems are not yet initialized).
> Fix nested RTTI calls and onInit handler

- src/scripting/LuaVM.cpp
- src/scripting/LuaVM.h
- src/scripting/LuaVM_Hooks.cpp
Calling ImGui from the `RunningState` hook causes random crashes. So this commit moves the `onDraw` handler back to the D3D12 hook, keeping the `onUpdate` in a new `RunningState` hook.
> Split update and draw handlers to RunningState and D3D12 hooks

- src/dllmain.cpp
- src/patches/OptionsPatch.cpp
As noted in #542, these two patches have been broken since v1.2.
After obtaining an old version of the game for comparison, I found the cause of the breakage: in v1.0x and v1.1x, `GameOptionInit()` used to be called twice for each setting, with the second call eventually ending up in `GameOption::Get()` (hooked by CET to redirect to `HookGameOptionGetBoolean()`). This is no longer the case, and `GameOptionInit()` is now only called once per setting, with the default value already provided.
This means that hooking `GameOption::Get()` (which was already failing anyway due to an outdated signature scan) no longer does anything useful, because the function is never called. Instead I have moved these settings to `HookGameOptionInit()`, and added explicit `SetBool()` calls for the settings that …
> Fix "disable AA" and "disable async compute" patches

- src/overlay/widgets/Console.cpp
- src/reverse/RTTIExtender.cpp
- src/reverse/RTTIExtender.h
- src/reverse/ResourceAsyncReference.cpp
- src/reverse/ResourceAsyncReference.h
- src/reverse/Type.cpp
- src/scripting/Scripting.cpp
```lua
spawnPosition = Game.GetPlayer():GetWorldTransform()
-- [Simple]
-- Spawn 'Character.Judy' just like prevention system
-- Optionally set appearance to 'judy_diving_suit'
judyEntityID = exEntitySpawner.SpawnRecord('Character.Judy', spawnPosition)
judyEntityID = exEntitySpawner.SpawnRecord('Character.Judy', spawnPosition, 'judy_diving_suit')
-- [Advanced]
-- Spawn base\quest\secondary_characters\judy.ent
-- Optionally set appearance to 'default'
-- Optionally set TweakDB record to 'Character.Judy' (VO/Name/Equipment/etc)
judyEntityID = exEntitySpawner.Spawn([[base\quest\secondary_characters\judy.ent]], spawnPosition)
judyEntityID = exEntitySpawner.Spawn([[base\quest\secondary_characters\judy.ent]], spawnPosition, 'default')
judyEntityID = …
```
> exEntitySpawner RTTIExtender

- src/reverse/RTTIHelper.h
- src/scripting/FunctionOverride.cpp
- src/scripting/Scripting.cpp
- Register global `PlayerPuppet.OnAction` handler as for pre patch 1.3.
- Override function by full name. Allows to observer / override all variants of overloaded function.
> Register global OnAction handler, override function by full name 

- src/reverse/RTTIMapper.cpp
- src/reverse/RTTIMapper.h
- src/scripting/FunctionOverride.cpp
1. Sanitize type names to be a valid Lua identifier.
This makes namespaced types added by redscript accessible in Lua. 
2. Force garbage collection for overridden functions of `inkGameController` and it's descendants.
In some cases, there seem to be issues with unreleased instances of `inkGameController` leading to crashes.
This was introduced when we started to properly wrap the context in `Handle<>`.
> Fix function override in some cases, add support for namespaced types from redscript

- src/reverse/BasicTypes.cpp
- src/reverse/BasicTypes.h
- src/reverse/Converter.cpp
- src/reverse/Enum.h
- src/scripting/Scripting.cpp
1. Added support of nulls for strong and weak references.
Assignment example: 
```lua
-- Set reference to null
self.resetConfirmationToken = nil
```
Parameter example: 
```lua
-- Omit optional task data
Game.GetDelaySystem():QueueTask(this, nil, "ResolveGameplayStateTask", gameScriptTaskExecutionStage.PostPhysics)
```
2. Added `IsDefined` helper function as in redscript. 
Checks if reference is not null and valid. Can be used on game object's field and lua variable.
3. Added `EnumInt` helper function as in redscript.
```lua
print(EnumInt(GameplayTier.Tier2_StagedGameplay)) -- 2ULL
```
4. Added support for `CRUID` type.  #612
```lua
local dialogLine = scnDialogLineData.new()
dialogLine.id = CRUID(12345)
```
5. Added support for `gamedataLocKeyWrapper` type.
```lua …
```
> Add support for nulls, CRUIDs, LocKeys, IsDefined() and EnumInt() helpers

- src/reverse/RTTIHelper.cpp
- src/scripting/Scripting.cpp
- Drop second implementation of `Scripting::ToRED()` which was very outdated. This was limiting what overridden functions can return.
- Fix `gamedataTDBIDHelper` helper that behaves the same as `gamedataTweakDBInterface`.
> Fix ToRED for overrides, fix TDBID helper

- src/reverse/RTTIHelper.cpp
There was a `TiltedPhoques::ScopedAllocator _(&s_scratchMemory);` when we call RTTI function. One of the `TiltedPhoques::Map` maps from outer scope can overflow while this override is active. During rehashing map acquires scratch allocator instead of default mimalloc.
> Fix TP STL allocations

- src/reverse/BasicTypes.cpp
- src/reverse/BasicTypes.h
- src/reverse/ClassReference.cpp
- src/reverse/ClassReference.h
- src/reverse/Enum.cpp
- src/reverse/Enum.h
- src/reverse/RTTIHelper.cpp
- src/reverse/RTTIMapper.cpp
- src/reverse/ResourceAsyncReference.cpp
- src/reverse/ResourceAsyncReference.h
- src/reverse/StrongReference.cpp
- src/reverse/StrongReference.h
- src/reverse/Type.h
- src/reverse/WeakReference.cpp
- src/reverse/WeakReference.h
- src/scripting/FunctionOverride.cpp
- src/scripting/FunctionOverride.h
- src/scripting/Scripting.cpp
- src/scripting/Scripting.h
1. Improved function overrides.
- When using `Override()` the handler receives the original function (or next in the override chain) as the last parameter
```lua
Override('PlayerPuppet', 'SetWarningMessage', function(_, message, wrappedMethod)
wrappedMethod('[Overridden] ' .. message)
end)
```
- The wrapped function can be called multiple times
```lua
Override('PlayerPuppet', 'GetGunshotRange', function(_, originalRangeFunc)
return originalRangeFunc() + originalRangeFunc()
end)
```
- If any of the overrides fail then the entire override chain also fails
- Observers can be called before and after the target function using `ObserveBefore()` and `ObserveAfter()`
```lua
ObserveBefore('PlayerPuppet', 'GetGunshotRange', function()
print('PlayerPuppet::GetGunshotRange::Before')
end) …
```
> Overrides and Variants

- src/scripting/FunctionOverride.cpp
- src/scripting/FunctionOverride.h
- src/scripting/LuaVM.cpp
- src/scripting/LuaVM.h
- src/scripting/LuaVM_Hooks.cpp
- src/scripting/ScriptContext.cpp
- src/scripting/ScriptContext.h
- src/scripting/ScriptStore.cpp
- src/scripting/ScriptStore.h
- src/scripting/Scripting.cpp
- src/scripting/Scripting.h
1. Use weak handle for `self` in overrides. This should decrease the number of unreleased references and make CET less dependent on garbage collection.
2. Reuse overridden functions on mods reload. This fixes a potential issue with the native function registry, which has a hard limit on the number of registered functions.
3. Support out params in overrides.  
To properly handle out params in overrides:  
- Accept all params in the handler
- Don't pass out params to the wrapped function
- Return all results from the handler
```lua
registerForEvent('onInit', function()
Override('SpatialQueriesSystem', 'SyncRaycastByCollisionGroup', function(_, a1, a2, a3, a4, a5, a6, wrapped)
-- Skip a4 here because it's an out param
local success, result = wrapped(a1, a2, a3, a5, a6)
print(success, …
```
> Overrides fixes, TweakDB hook

- src/overlay/widgets/TweakDBEditor.cpp
- src/reverse/RTTIMapper.cpp
- src/reverse/RTTIMapper.h
- src/reverse/TweakDB.cpp
- src/reverse/TweakDB.h
- src/scripting/FunctionOverride.cpp
- src/scripting/ScriptContext.cpp
- src/scripting/Scripting.cpp
- Fixed random crashes for very frequently called overrides (such as `GameObject.OnGameAttached` and `GameObject.OnDetach` on game reload).
- Fixed random crashes for hotkeys and inputs (for example, binding the mouse wheel had a very high chance of causing crashes).
- Fixed potential issues when CET mods that modify TweakDB are used with TweakDBext mods at the same time.
- Added the ability to add new free flats to TweakDB.
---
With more extensive use of overrides a new issue was discovered: the Lua stack could be corrupted because `TiltedPhoques::Vector<sol::object> args;` was placed before acquiring the lock `chain.pScripting->GetState()` allowing another thread in the multithreaded environment to perform garbage collection, call Lua functions, and corrupt references in `args`.
This …
> Stability hotfix for overrides

- src/reverse/ClassReference.cpp
- src/reverse/ClassReference.h
- src/scripting/FunctionOverride.cpp
- Fixed random crashes when overridden method has a script reference parameter. 
- Fixed random crashes when working with game structs.
> Fix script references in overrides, fix structs

- src/kiero/kiero.cpp
See title.
The vtable globals are actually never used (they were added in f21c0b2 but their usage was reverted in 246af04 without removing the globals themselves). So simply removing them completely would also work, especially since the Win 10 D3D12 hooks are now applied to the game instead of the D3D12/DXGI vtables anyway, and Win 7 also doesn't actually need them either, but I've left them for now.
It's possible that the new D3D12 hooking method can be made to work with D3D12on7 as well so that kiero can just be removed entirely, but I haven't really looked into that because the current method is pretty low maintenance at least.
> Fix crash to desktop on Windows 7

- src/reverse/TweakDB.cpp
- src/reverse/TweakDB.h
- src/scripting/Scripting.cpp
Currently CET's implementation of `CreateRecord`, `CloneRecord`, and `DeleteRecord` only allow the first parameter to be a string value. Update the functions to allow `TweakDBID`s for the first parameter.
Example:
```lua
-- Get the sticky frag grenade record
sticky_grenade = TweakDB:GetRecord("Items.GrenadeFragSticky")
-- Create a clone of "Items.GrenadeFragSticky" with the name "Items.GrenadeFragStickyNew"
TweakDB:CloneRecord(sticky_grenade:GetID() + "New", sticky_grenade:GetID())
-- Get the new record
sticky_grenade_new = TweakDB:GetRecord("Items.GrenadeFragStickyNew")
-- or
sticky_grenade_new = TweakDB:GetRecord(sticky_grenade:GetID() + "New")
-- manipulate the new record as needed
-- delete record many different ways
TweakDB:DeleteRecord(sticky_grenade_new:GetID()) …
```
> Allow the use of TweakDBIDs in Create, Clone and DeleteRecord

- src/Paths.cpp
- src/Paths.h
- src/overlay/widgets/TweakDBEditor.cpp
Adds support for reading and importing entries from the TweakDB created by REDMod.
The `HasREDModTweakDB` function isn't really needed since you can just check the file directly and doesn't have to be public if it's kept, but maybe it's good to have it in there if there's a need to check later. Not sure where though. Maybe it could be used to update the TweakDB Editor window to reflect that CET found a modified TweakDB. But if that's the case it might be better to move it to a function that checks that it was properly loaded like how `IsInitialized` is used.
Let me know what you think.
> TweakDBEditor: Add support for REDMod modified TweakDB

- src/sol_imgui/sol_imgui.h
Forgot to expose DisplayStart and DisplayEnd in #739
> Expose extra properties in ImGuiListClipper

- src/overlay/widgets/Console.cpp
- src/overlay/widgets/LogWindow.cpp
- src/scripting/LuaVM_Hooks.cpp
Smaller inconveniences fixed, not major bugs.
Concerns Console and LogWindow mostly.
Console trims commands now and also checks for empty strings before execution and saving command to history.
LogWindow should not allow you to start selecting multiple lines (at least visually).
LogChannel color changes for ~DEBUG~ and ASSERT channels (ASSERT is now red, ~DEBUG logs in Console window are printed as regular info~).
Striked got merged with previous PR from psiberx (missed it)
> Fix Console history registering empty entries and LogWindow issues

- src/reverse/RTTIMapper.cpp
- src/reverse/Type.cpp
- src/scripting/LuaSandbox.cpp
- src/scripting/LuaSandbox.h
- src/scripting/Sandbox.cpp
- src/scripting/Sandbox.h
- src/scripting/Scripting.cpp
- Returned `Vector3` type to previous behavior
- Enabled overrides for new `onHook` event
- Disabled warning "Member not found" which was more annoying than helpful and could in rare cases result in c++ exceptions
- Adjusted the global fallback table for sandboxes to not be confused with environments (the global table must only be used as a lookup fallback table and never as an environment)
- Removed unused `LuaSandbox::ExecuteFile` and `LuaSandbox::ExecuteString`
> More hotfixes for 1.21.0

- src/overlay/Overlay.cpp
- src/overlay/widgets/Console.cpp
- src/overlay/widgets/Console.h
- src/overlay/widgets/GameLog.cpp
- src/overlay/widgets/GameLog.h
- src/overlay/widgets/LogWindow.cpp
- src/overlay/widgets/LogWindow.h
- src/scripting/LuaSandbox.cpp
- src/scripting/LuaVM.cpp
- src/scripting/LuaVM.h
- src/scripting/Sandbox.cpp
- src/scripting/Sandbox.h
- src/scripting/ScriptContext.cpp
- src/scripting/ScriptContext.h
- src/scripting/ScriptStore.cpp
- src/scripting/ScriptStore.h
- src/scripting/Scripting.cpp
- src/scripting/Scripting.h
Idea is to give mods better logging facilities to both, console and their own logs (which they now only have in form of a file).
This should enable colored console output and allow mods to enable their own logging window at will, which would contain only their log. Logging into these sinks is provided via new consoleLog and modLog functions.
consoleLog works also in console, is meant as a replacement for print (print is still supported and behaves as consoleLog.info)
modLog is mod-specific, points to mod-specific logger and log window (aliases spdlog for backwards compatibility)
Both of these new interfaces support printing of multiple arguments (converts them to strings and concats them like print did previously).
This is upgrade over previous spdlog implementation, which it inherits …
> Better mod logging

- src/Options.cpp
- src/Options.h
- src/VKBindings.cpp
- src/d3d12/D3D12_Functions.cpp
- src/d3d12/D3D12_Hooks.cpp
- src/dllmain.cpp
- src/overlay/Overlay.cpp
- src/overlay/Overlay.h
- src/overlay/widgets/Bindings.cpp
- src/overlay/widgets/Settings.cpp
- src/overlay/widgets/Settings.h
- src/patches/OptionsPatch.cpp
Keeps previously opened widgets opened after game shuts down when it next launches.
Also organize options a bit better and fix mod being able to draw during first time setup.
Dependency for https://github.com/yamashi/CyberEngineTweaks/pull/754
Continued in #754 (gave it separate file there and some other tweaks)
> Persistent state for Overlay widget toggles

- ida/patterns.py
- src/d3d12/D3D12.cpp
- src/d3d12/D3D12.h
- src/d3d12/D3D12_Functions.cpp
- src/dllmain.cpp
- src/reverse/Addresses.h
- src/scripting/GameDump.cpp
- src/scripting/GameDump.h
- src/scripting/GameHooks.cpp
- src/scripting/GameHooks.h
- src/scripting/LuaVM.cpp
- src/scripting/LuaVM.h
- src/scripting/LuaVM_Hooks.cpp
- src/scripting/Scripting.cpp
- src/stdafx.h
If user toggles overlay during early startup, focuses on console input and presses overlay toggle hotkey, deadlock happens.
ImGui got locked in main thread and render thread due to some ImGui things...
We do not access platform things from present now, modified a bit log there.
Removed lock of ImGui in OnWndProc.
Reworked GameMainThread class as part of this, used it for managing tasks for each state type tick function.
Currently used in LuaVM and D3D12, along with dump job.
Dependency for https://github.com/yamashi/CyberEngineTweaks/pull/754
> Fix possible deadlock on startup

- src/reverse/RTTIHelper.cpp
- src/scripting/Scripting.cpp
- Added more memory for RTTI calls and overrides as one upcoming mod hits the limit
- Fixed possible crash when lua value cannot be converted or there's not enough memory
> Increase memory for RTTI helpers

- src/reverse/TweakDB/TweakDB.cpp
- src/reverse/TweakDB/TweakDB.h
- src/reverse/Type.cpp
- src/reverse/Type.h
- src/scripting/FunctionOverride.cpp
- Fixed issue introduced by sol2 v3.3.0 where `nil` doesn't qualify as _anything_ in _some_ contexts.
- Improved context handling in function overrides (fixes crash on latest patch).
> Fix nil assignments in lua

- src/VKBindings.cpp
Fixes #764 
Function keys f13 to f24 work, but are displayed as "Unknown" in the UI.
Adding f13 to f24 to GetSpecialKeyName seems to work.
Tested by rebinding some keys to the above function keys as I don't have a keyboard with physical f13 to f24 keys.
> Fix function keys f13 to f24 displaying as Unknown in the UI

- src/scripting/LuaSandbox.cpp
This fixes
```
init.lua:28: attempt to call field 'LoadTexture' (a nil value)
```
> fix ImGui.LoadTexture nil in ImGui table

- src/reverse/LuaRED.h
Fixed incorrect behavior when float passed as int: it would lead to cryptic error "sol: runtime error: stack index -1, expected number, received number: not a numeric type or numeric string" and memory leaks.
> Fix number conversion

- src/overlay/widgets/TweakDBEditor.cpp
Accidentally left in... This caused cache rebuild to early-report that initialization finished, leading to possibility of race conditions.
> Fix typo in TweakDBEditor initialization causing it to "finish" sooner

- src/reverse/RTTIExtender.cpp
The offset leads to the function before the constructor being partially executed, leading to an access violation
> remove offset from gameIGameSystem constructor call

- src/scripting/FunctionOverride.cpp
- src/scripting/LuaVM_Hooks.cpp
- Fixed `ScriptReference` handling in overrides
- Fixed TweakDB related crashes caused by hash collisions when runtime changes tracking is enabled
> Patch 2.0 fixes

- ida/patterns.py
- src/reverse/Addresses.h
Fixed a typo in `patterns.py` for `ToStringDEBUG`.
> Fix ToStringDEBUG addr

- src/CET.cpp
- src/Utils.cpp
- src/Utils.h
- src/scripting/LuaSandbox.cpp
- src/scripting/LuaSandbox.h
- src/scripting/LuaVM_Hooks.cpp
- src/scripting/ScriptContext.cpp
- src/scripting/Scripting.h
When launching the game through Mod Organizer 2, CET mods don't work
That is because 
- (1) the luaVM is started too soon (before MO2s virtual file system has started)
- and (2) because MO2 overlays 3 different directories in its VFS: the base game dir, the virtualized mod dir, and the "overwrite" dir where runtime-created files are stored.
Any mod that creates files at runtime (that is ALL CET mods since the sandbox db gets created at runtime) will fail since the "overwrite" directory escapes the mod sandbox.
This PR does two things:
1. It delays the luaVM init slightly so that CET mods get detected after UVFS did its thing
2. More problematically, it allows lua paths outside the mod sandbox under certain conditions:
- when the game is launched through MO2 (we detect `usvfs_x64.dll`)
- …
> uvfs support for CET with MO2 

- src/scripting/LuaSandbox.cpp
makes the MO2 folder path checking much simpler and doesn't rely on "overwrite" anymore as that folder name can be changed arbitrarily by the user.
mentions #890
> fix: no explicit mo2 folder name checking

- src/scripting/LuaSandbox.cpp
- src/scripting/LuaSandbox.h
One more uvfs fix for relative file paths.
PR for @seberoths and @zashs suggestions.
~~- api addition for `dir()`: add relativePath property~~
- internal relative() resolve in luasandbox for uvfs
- restore original relativePath check for sandbox
closes #890
> fix: relative file paths for uvfs

- src/CET.cpp
- src/Options.cpp
- src/Options.h
- src/overlay/widgets/Settings.cpp
- src/scripting/LuaVM.h
- src/scripting/LuaVM_Hooks.cpp
- src/scripting/Scripting.cpp
- src/scripting/Scripting.h
Resolves #899 .
See comment https://github.com/maximegmd/CyberEngineTweaks/issues/899#issuecomment-1784053997
> Add `sol::lib::jit` to actually enable JIT ( resolves #899 )

- src/reverse/Addresses.h
- src/reverse/ResourceAsyncReference.cpp
- src/scripting/GameOptions.cpp
- Fixed `exEntitySpawner`
- Partially fixed `GameOptions`
> Various fixes

- src/overlay/widgets/LogWindow.cpp
Currently red on blue errors are almost unreadable in the console. This PR changes the background of the console content to semi-transparent black and changes the the error color to a slightly brighter shade of red.
Before:
After:
> Improved readability of the console window, especially errors

- src/overlay/widgets/Settings.cpp
I fixed the description of the Disable V-sync setting because it was seemingly copy-pasted to the wrong Fix Minimap Flicker setting. I modified that settings description too but am not quite sure what to write in there because I never actually experienced the issue myself.
> Fix "Disable VSync" settings description

- src/imgui_impl/win32.cpp
- src/sol_imgui/README.md
- src/sol_imgui/sol_imgui.h
- Brings back the previously removed ImGui input functions, by reverting the changes from 4f23722 (They were removed back when ImGui functions could be called from anywhere, but now they are limited to `onDraw`)
- Verified that those input functions can only get called from `onDraw`
- Added some additional keys, like CTRL and Shift key (Needed for e.g. CTRL-C and other universal shortcuts often used)
- @maximegmd Please let me know if there are any issues with these changes
> Added back ImGui Input functions

- src/Image.h
- src/reverse/Addresses.h
- Updated RED4ext.SDK
- Updated AddressHashes::CPhotoMode_SetRecordID
- Note: CScript_RegisterMemberFunction seems to not be used by anything
Seems to work by my untrained eye, I can run around using CET mods and spawn NPCs
> Small fixes for Patch 2.13

- src/Image.h
- src/reverse/Addresses.h
Note: RED4ext.SDK is currently from my branch with 2.2 update, probably should wait until it gets merged into mainline?
> Added compatibility with Patch 2.2

- src/imgui_impl/win32.cpp
> Fix ImGui mouse position when render resolution is different than window resolution

- src/Image.h
- src/reverse/Addresses.h
> Patch 2.21 support

- src/d3d12/D3D12.cpp
- src/d3d12/D3D12.h
- src/d3d12/D3D12_Functions.cpp
- src/dllmain.cpp
- src/window/window.cpp
I have been getting several reports from Special K users of crashes when using this mod, and finally had some time to investigate.
Primary issues found:
1. Code to show/hide the hardware cursor does not handle pathological case where something is preventing the cursor's state from changing -- infinite loop.
2. DisableThreadLibraryCalls (...) used in a DLL that uses MSVCRT managed thread_local storage.
3. A single command allocator/list was being used for all frame contexts, despite creating per-context allocators.
4. The game's window title was being used to find the main window, but this is highly volatile; use window class name instead.
> Fix overlay rendering issues that lead to crashing when other overlays are present

- .gitignore
- src/CETVersion.h.in
- src/Options.cpp
- src/scripting/Scripting.cpp
- src/stdafx.h
- src/xmake/CETVersion.h.in
- src/xmake/Resource.rc.in
- xmake.lua
* Version info based off git information
* Add autogenerated resource file so the final DLL has some version info
* Cleaner inclusion of autogenerated files (prevents constant stdafx.h rebuilds and puts resulting files into some more normal directory)
* Fix #894
> Better versioning

- src/d3d12/D3D12.cpp
- src/d3d12/D3D12_Functions.cpp
- src/d3d12/D3D12_Hooks.cpp
- src/overlay/Overlay.cpp
- src/overlay/Overlay.h
- src/reverse/Addresses.h
Also makes sure that we actually have 200 descriptors for texture, we allocated only 3 (ImGui really needs only 1 though per viewport, we have one in main) but allowed up to 200.
> Fix ImGui spam of ShowCursor/HideCursor
