maximegmd/CyberEngineTweaks

PROTON.md
README.md

This commit changes the README to add an extra link to one additional file.
The new file, `PROTON.md` gives the user a guide on setting the game up in Proton.

Added Proton guide to fix yamashi/PerformanceOverhaulCyberpunk#69

---

PROTON.md

I do believe you have to add the library you selected to the list first so these instructions would reflect.

Small winecfg instruction adjustments

---

PROTON.md

Would adding pictures to the installation help? I can provide those.
Address #81

Added Winetricks instructions for GOG version users.

---

src/Options.cpp
src/Options.h
src/overlay/Overlay.cpp
src/overlay/Overlay.h
src/reverse/RTTI.h
src/reverse/Scripting.cpp

- Automatically resize console output area to match window.
- Copy selected console output line to current input.
- Checkbox to enable auto scrolling of output area.
- Improved parsing of commands.
- More sanity checking on executing command function.
- Don't require flag 0 (global?) on command functions.
- Don't block all window messages, block specific ones instead.

Console improvements.

---

.github/workflows/build.yml

Fix CI build - checkout submodules

---

.github/workflows/build.yml

this will fix yaml syntax
sorry

fix CI yaml

---

src/reverse/Scripting.cpp

Right now we cannot handle other types of parameters, passing an incorrect type would likely cause the game to crash.

Add sanity check for console parameters

---

src/Image.h
src/Options.cpp

Fix image version logging.

---

src/reverse/BasicTypes.cpp
src/reverse/BasicTypes.h
src/reverse/Converter.cpp
src/reverse/Scripting.cpp

- Add Vector3.
- Add To* lua functions for constructing user types from a Lua table.
- Add additional user type constructors. eg Vector4.new(1) is now possible.
- Cleanup/fixes to user type ToString().

Improvements to user types.

---

src/overlay/Overlay.cpp

Use ImGuiListClipper to draw just visible output lines

---

src/scripting/Scripting.cpp

Dump contents in Lua only if handle is not nil

---

src/kiero/kiero.cpp

Fixes a leftover TODO requested in #318 re: use of `CComPtr<T>` instead of `IUnknown*`. Also some other minor changes, see commit message.
I know the changes to Direct3D 9-11 aren't going to be used by CET, but they still reduce the LOC count in a file that's (IMO) quite hard to read due to its size.
This PR includes the changes made to kiero in #331 so there should be no merge conflicts.

Kiero refactor

---

src/overlay/Overlay.h
src/overlay/Overlay_D3D12.cpp
src/overlay/Overlay_Hooks.cpp

Fixes a leftover TODO from #318.

D3D12On7 cleanup

---

src/overlay/Overlay.cpp
src/overlay/Overlay.h
src/overlay/Overlay_D3D12.cpp
src/overlay/Overlay_Hooks.cpp
xmake.lua

For now, just a draft so @Mattiwatti knows what changes I'm making in real time better...
This pull request will try to resolve issues with resolution changes, which should help fix issues with fullscreen.
Note that this would be for D3D12, not D3D12on7. Latter will be worked on hopefully by Matti here.

D3D12 - detect resolution changes

---

scripts/autoexec.lua
src/Options.cpp
src/Options.h
src/dllmain.cpp
src/kiero/kiero.cpp
src/kiero/kiero.h
src/overlay/Overlay.cpp
src/overlay/Overlay.h
src/overlay/Overlay_D3D12.cpp
src/overlay/Overlay_Hooks.cpp
src/overlay/imgui_impl_win32.cpp
src/overlay/imgui_impl_win32.h
src/patches/Avx.cpp
src/patches/DisableBoundaries.cpp
src/patches/DisableIntroMovies.cpp
src/patches/DisableVignette.cpp
src/patches/EnableDebug.cpp
src/patches/OptionsPatch.cpp
src/patches/RemovePeds.cpp
src/patches/SkipStartScreen.cpp
src/patches/Smt.cpp
src/patches/VirtualInput.cpp
src/scripting/ScriptStore.cpp
src/scripting/Scripting.cpp
xmake.lua

Fixes #329, #319, #286, #283, #275, #270, #260, #257, #236, #228, #193, #186, #137
Following text is from initial PR, does not contain all changes!
> Main one here being more reliable resize hook for Windows 10 and removal of less reliable one pulled before.
> 
> It seems it was not as bulletproof as first thought... So even though I wanted to left it in as partial fix at least for Windows 7, I rather removed it.
> 
> Other major change is complete refactor of kiero, as we already made it our own I'd say.
> I also expanded its method table and would like to add some more logic into methods table (prolly create some massive enum, so we it can be more easily seen to what we try to hook right from code... plain numbers suck balls).

Batch of fixes and improvements (+some refactor of things thrown into it)

---

src/Options.cpp
src/scripting/Scripting.cpp

Yeah, just this small fix... 
Relates to #345

Fix crash if mods folder does not exist

---

src/reverse/BasicTypes.h
src/reverse/Converter.cpp
src/reverse/Enum.cpp
src/reverse/Enum.h
src/reverse/Type.cpp
src/reverse/Type.h
src/scripting/Scripting.cpp

Added Enum support with number<->Enum<->string
Added ref<->wref simple implicit cast
Added more dump support
Temp fix to allow searching function overloads

More type support, more dumps, more accessible functions

---

src/reverse/Type.cpp
src/reverse/Type.h
src/scripting/Scripting.cpp

This PR improves the output of `Dump()` by exposing param name/type in functions, and return types for both functions and properties.
It also changes to using `name2` of functions, as that appears to be cleaner and does not have trailing semicolon and overload(?) type in the name.
I've put the hash output as an optional flag when calling `Dump()`, so `Dump(obj, true)` will also dump hashes.
Output of `Dump(Game.GetTransactionSystem())`
```
{
name: gameTransactionSystem,
functions: {
PrefetchItemAppearance(obj: handle:gameObject, itemID: gameItemID, newAppearanceName: CName),
ChangeItemAppearance(obj: handle:gameObject, itemID: gameItemID, newAppearanceName: CName, useSuffixes: Bool),
ChangeItemAppearanceWithItemData(),
GetItemAppearance(obj: handle:gameObject, itemID: gameItemID) => …
```

Add param and return type data to Dump()

---

src/console/Console.cpp
src/d3d12/D3D12.cpp
src/d3d12/D3D12.h
src/scripting/LuaVM.cpp
src/scripting/LuaVM.h
src/scripting/ScriptContext.cpp
src/scripting/ScriptContext.h
src/scripting/Scripting.cpp
src/scripting/Scripting.h

- rename ReloadScripts to ReloadAllMods
- fix onInit not being called it ReloadAllMods 
- add ReloadAllMods to Console as a button
- fix GetDisplayResolution return value
- add onShutdown handler to LuaVM so mods can properly deinitialize if they need it

Changes and additions

---

src/reverse/BasicTypes.cpp
src/reverse/BasicTypes.h
src/reverse/ClassReference.cpp
src/reverse/ClassReference.h
src/reverse/SingletonReference.cpp
src/reverse/SingletonReference.h
src/reverse/StrongReference.cpp
src/reverse/StrongReference.h
src/reverse/Type.cpp
src/reverse/Type.h
src/reverse/WeakReference.cpp
src/reverse/WeakReference.h
src/scripting/Scripting.cpp
src/stdafx.h

Upgrade RED4ext

---

src/sol_imgui/sol_imgui.h

Fixed `PushStyleVar()` and `PopStyleVar()` binding in `sol_imgui.h`
#399

Fixed PushStyleVar() and PopStyleVar() binding

---

src/Options.h
src/console/Console.cpp
src/d3d12/D3D12_Functions.cpp

Configurable JSON file, supporting local font.  I tested Chinese, Japanese and Korean and worked well.
[fonts.zip](https://github.com/yamashi/CyberEngineTweaks/files/5832003/fonts.zip)

Add font support

---

src/dllmain.cpp
src/scripting/Scripting.cpp

Just tiny little fix for debug mode building :P 
Includes were missing it seems.

Fix building of debug config

---

src/d3d12/D3D12.h
src/d3d12/D3D12_Functions.cpp
src/dllmain.cpp
src/scripting/Scripting.cpp

Fix DX12 regression

---

src/CET.cpp
src/VKBindings.cpp
src/VKBindings.h
src/d3d12/D3D12.cpp
src/d3d12/D3D12.h
src/d3d12/D3D12_Functions.cpp
src/overlay/Overlay.cpp
src/overlay/Overlay.h

Found a way to solve this elegantly enough I believe :P 
Is fully compatible with #454 and #453

Fix HK handler causing sol state corruption leading to crash

---

src/sol_imgui/sol_imgui.h

Removed the redundant prefix in ImGuiMouseButton enum

Removed the redundant prefix in ImGuiMouseButton enum

---

src/sol_imgui/sol_imgui.h

Implemented bindings for ImDrawList
@WSSDude420 need to add `ImDrawCornerFlags` into the whitelist https://github.com/yamashi/CyberEngineTweaks/pull/454

Implement ImDrawList

---

src/scripting/LuaSandbox.cpp

Removed redundant __Game __Type and added TweakDB added with last PR.

Modify sandbox whitelist

---

src/sol_imgui/README.md
src/sol_imgui/sol_imgui.h

When https://github.com/xmake-io/xmake-repo/pull/287 get merged

Update binding to imgui1.8.1

---

src/sol_imgui/sol_imgui.h

Add missing CellPadding

---

src/scripting/LuaSandbox.cpp

Fix os.rename and os.remove

---

src/Options.cpp
src/Options.h
src/dllmain.cpp
src/overlay/widgets/Settings.cpp
src/overlay/widgets/Settings.h
src/patches/Smt.cpp

Add AMD SMT patch

---

src/Options.cpp
src/Options.h
src/Paths.cpp
src/VKBindings.cpp
src/VKBindings.h
src/overlay/Overlay.cpp
src/overlay/Overlay.h
src/overlay/widgets/Bindings.cpp
src/overlay/widgets/Bindings.h
src/overlay/widgets/HelperWidgets.cpp
src/overlay/widgets/Widget.h
src/scripting/LuaSandbox.cpp
src/scripting/LuaSandbox.h
src/scripting/Sandbox.cpp
src/scripting/ScriptContext.cpp
src/scripting/Scripting.cpp
src/scripting/Scripting.h

Fix #424 and #465
Changes:
- scroll wheel support (in both axes)
- added registerInput for single inputs
- renamed Hotkeys to Bindings (added needed compatibility checks)
- as we have two input styles now, hotkeys are marked with [HK] prefix inside bindings menu
- add functions to get key bind string
- expose IsBound and GetBind (string version) to particular Sandbox environments

Enhance VKBindings + modify everything else accordingly

---

src/overlay/widgets/TweakDBEditor.cpp
src/overlay/widgets/TweakDBEditor.h

supports loading archivehashes.txt
can now search through record flats
some refactoring is required to lower the memory usage but I don't think I will be able to do it anytime soon
so many flats...

TweakDBEditor

---

src/sol_imgui/sol_imgui.h

Few small changes, followed `Breaking changes` section of 1.82 release notes and applied that what we have implemented (which was very tiny chunk).

Update ImGui bindings to accomodate for 1.82 breaking changes

---

src/scripting/LuaSandbox.cpp
src/sol_imgui/sol_imgui.h

- Add missing TreePop
- Add ImGuiDrawFlags into whitelist

Add missing ImGui bindings stuff

---

src/reverse/TweakDB.cpp
src/reverse/TweakDB.h
src/scripting/Scripting.cpp

TweakDB QoL
```lua
TweakDB:SetFlats('Character.Judy', {
level = 99,
tags = { 'Immortal' }
});
```

added TweakDB::SetFlats

---

src/reverse/RTTIExtender.cpp
src/reverse/RTTIExtender.h
src/scripting/Scripting.cpp

```lua
transform = Game.GetPlayer():GetWorldTransform()
entityID = WorldFunctionalTests.SpawnEntity('base\\quest\\secondary_characters\\judy.ent', transform, '')
entity = Game.FindEntityByID(entityID)
WorldFunctionalTests.DespawnEntity(entity)
```

add WorldFunctionalTests RTTI

---

src/Options.cpp
src/Options.h
src/dllmain.cpp
src/overlay/widgets/Settings.cpp
src/overlay/widgets/Settings.h
src/patches/MinimapFlicker.cpp

Waits for test. From pure patching side, this works. Question is if it does what is advertised 😄 
Cant judge, I honestly dont see difference 🤷 
Kudos to DemonRed and gibbed on our Discord
https://discord.com/channels/705931815109656596/716477925670518784/850437250545877022

Add patch for minimap flicker

---

src/reverse/TweakDB.cpp

fix for https://discord.com/channels/717692382849663036/795037494106128434/871885536695046144
and update RED4ext.SDK: https://github.com/WopsS/RED4ext.SDK/pull/39

fix TweakDB default values

---

src/overlay/widgets/TweakDBEditor.cpp

SetTooltip calls sprintf, a tooltip with "%whatever" crashes the game

fix ImGui::SetTooltip formatting

---

src/scripting/LuaVM_Hooks.cpp

- Fix game log by using `ref.ref` as it can be replaced with another `CString` instance instead of modifying `text` (in this case `text` stays empty).
- Use `CName` for channel instead of `uint64_t`.
- Add special always-on debug channel so redscript mods can print without enabling full game log, which can be very spamy.
```
public static func LogDebug(const str: script_ref<String>) -> Void {
LogChannel(n"DEBUG", str);
}
```

Fix game log and add always-on debug channel

---

README.md

Fix #599, Readme update for version 1.16.0

---

src/reverse/RTTIExtender.cpp

fix exEntitySpawner

---

src/Options.cpp
src/Options.h
src/Utils.cpp
src/VKBindings.cpp
src/VKBindings.h
src/d3d12/D3D12.cpp
src/d3d12/D3D12.h
src/d3d12/D3D12_Functions.cpp
src/imgui_impl/dx12.cpp
src/overlay/Overlay.cpp
src/overlay/Overlay.h
src/overlay/widgets/Bindings.cpp
src/overlay/widgets/LogWindow.cpp
src/overlay/widgets/Settings.cpp
src/overlay/widgets/TweakDBEditor.cpp
src/overlay/widgets/TweakDBEditor.h
src/reverse/RTTIMapper.cpp
src/scripting/LuaSandbox.cpp
src/scripting/ScriptStore.cpp
src/scripting/Scripting.cpp
src/sol_imgui/sol_imgui.h

Each commit should address some issue reported after release.
Should be ready to ship.

Hotfix for 1.21.0

---

src/overlay/widgets/TweakDBEditor.cpp
src/reverse/RTTIHelper.cpp
src/reverse/RTTIHelper.h
src/scripting/Scripting.cpp

- Fix flats in TweakDB Editor
- Initialize `RTTIHelper` for `onHook` event

More hotfixes for 1.21.0

---

src/Options.cpp
src/Options.h
src/VKBindings.cpp
src/d3d12/D3D12_Functions.cpp
src/d3d12/D3D12_Hooks.cpp
src/dllmain.cpp
src/overlay/Overlay.cpp
src/overlay/Overlay.h
src/overlay/widgets/Bindings.cpp
src/overlay/widgets/Settings.cpp
src/overlay/widgets/Settings.h
src/patches/OptionsPatch.cpp

Keeps previously opened widgets opened after game shuts down when it next launches.
Also organize options a bit better and fix mod being able to draw during first time setup.

Persistent state for Overlay widget toggles

---

src/CET.cpp
src/CET.h
src/Options.cpp
src/Options.h
src/Paths.cpp
src/Paths.h
src/PersistentState.cpp
src/PersistentState.h
src/overlay/Overlay.cpp
src/overlay/Overlay.h
src/overlay/widgets/Console.cpp
src/overlay/widgets/Console.h
src/overlay/widgets/GameLog.cpp
src/overlay/widgets/GameLog.h
src/overlay/widgets/LogWindow.cpp
src/overlay/widgets/LogWindow.h
src/stdafx.h

- Persistent state in its own class (and file)
- Now includes console history!
- Maximum number of lines for history configurable from config.json
- Persistency of console history is controlled via option in config.json
Conflicts with PRs #753 #757

Persistent console history, small cleanup of persistent state

---

src/overlay/widgets/Console.cpp
src/reverse/RTTIHelper.cpp
src/reverse/RTTIHelper.h
src/scripting/FunctionOverride.cpp

Building `CStackFrame` and bytecode for arguments on our side now, which allows to:
- Pass optional params as intended
- Call a couple more functions

Improve RTTI calls

---

README.md

The README should be updated, since currently it says that
```Current version works with 1.52 game version```

Update game-version compatibility in README.md

---

src/Image.cpp

Current message is a bit cryptic so I thought you could use something easier to understand.

More descriptive error log for unrecognized game version + build instructions

---

src/scripting/FunctionOverride.cpp

Fixes function override when the function was called with a different implementation of `CScriptStack`.

Fix more overrides

---

src/reverse/NativeProxy.cpp
src/reverse/NativeProxy.h
src/reverse/StrongReference.cpp
src/reverse/WeakReference.cpp
src/scripting/Scripting.cpp

```lua
local listener
local statsListener
registerForEvent('onInit', function()
listener = NewProxy({
OnWeaponStateChange = {
args = {'Int32'},
callback = function(state)
print('[Proxy] OnWeaponStateChange', Enum.new('gamePSMRangedWeaponStates', state))
end
},
OnCursorMove = {
args = {'handle:inkPointerEvent'},
callback = function(event)
print('[Proxy] OnCursorMove', GameDump(event:GetScreenSpacePosition()))
end
}
})
statsListener = NewProxy('ScriptStatsListener', {
OnStatChanged = {
args = {'StatsObjectID', 'gamedataStatType', 'Float', 'Float'},
callback = function(ownerID, statType, diff, value)
print('[Proxy] OnStatChanged', ownerID.entityHash, statType, diff, value)
end
}
})
Observe('PlayerPuppet', 'PlayerAttachedCallback', function(player)
local blackboardPSM = …
```

Script-to-Lua proxies

---

src/scripting/LuaSandbox.cpp

https://discord.com/channels/717692382849663036/795037494106128434/1126872581799153744

Fix os.rename() in lua sandbox

---

src/Options.cpp
src/PersistentState.cpp
src/VKBindings.cpp

fixing https://discord.com/channels/717692382849663036/792728454079447041/1133979036390010981

fix crash when parsing invalid json files

---

README.md

Update supported game version in readme

Update README.md for 2.0

---

src/reverse/Relocation.h
src/scripting/FunctionOverride.cpp
src/stdafx.h
xmake.lua

Added address resolver override so CET can use original SDK with own address resolver.

Support latest SDK

---

.github/workflows/build.yml
.gitignore
xmake.lua

This should help out debugging crash reports in the wild, as most people will not compile CET themselves lol
Not sure about the packaging hack to get .pdb path, is there a more XMakey way?

PDB generation for the release artifacts
